import tkinter as tk
import time

i = 0

def myClick():
    global i
    print("Robot is moving to the selected location")
    time.sleep(5)
    if i == 0:
        print("Lift the Shelf")
        i += 1
    else:
        print("Put the Shelf down")
        i -= 1

# Window
window = tk.Tk()
window.title("Choose the location")

# Widget
button00 = tk.Button(window, text="A1", padx=20, pady=20, command=myClick)
button01 = tk.Button(window, text="A2", padx=20, pady=20, command=myClick)
button02 = tk.Button(window, text="A3", padx=20, pady=20, command=myClick)
button03 = tk.Button(window, text="A4", padx=20, pady=20, command=myClick)
button04 = tk.Button(window, text="A5", padx=20, pady=20, command=myClick)
button05 = tk.Button(window, text="A6", padx=20, pady=20, command=myClick)
button06 = tk.Button(window, text="A7", padx=20, pady=20, command=myClick)
button07 = tk.Button(window, text="A8", padx=20, pady=20, command=myClick)
button08 = tk.Button(window, text="A9", padx=20, pady=20, command=myClick)
button09 = tk.Button(window, text="A10", padx=20, pady=20, command=myClick)

button10 = tk.Button(window, text="B1", padx=20, pady=20, command=myClick)
button11 = tk.Button(window, text="B2", padx=20, pady=20, command=myClick)
button12 = tk.Button(window, text="B3", padx=20, pady=20, command=myClick)
button13 = tk.Button(window, text="B4", padx=20, pady=20, command=myClick)
button14 = tk.Button(window, text="B5", padx=20, pady=20, command=myClick)
button15 = tk.Button(window, text="B6", padx=20, pady=20, command=myClick)
button16 = tk.Button(window, text="B7", padx=20, pady=20, command=myClick)
button17 = tk.Button(window, text="B8", padx=20, pady=20, command=myClick)
button18 = tk.Button(window, text="B9", padx=20, pady=20, command=myClick)
button19 = tk.Button(window, text="B10", padx=20, pady=20, command=myClick)

button20 = tk.Button(window, text="C1", padx=20, pady=20, command=myClick)
button21 = tk.Button(window, text="C2", padx=20, pady=20, command=myClick)
button22 = tk.Button(window, text="C3", padx=20, pady=20, command=myClick)
button23 = tk.Button(window, text="C4", padx=20, pady=20, command=myClick)
button24 = tk.Button(window, text="C5", padx=20, pady=20, command=myClick)
button25 = tk.Button(window, text="C6", padx=20, pady=20, command=myClick)
button26 = tk.Button(window, text="C7", padx=20, pady=20, command=myClick)
button27 = tk.Button(window, text="C8", padx=20, pady=20, command=myClick)
button28 = tk.Button(window, text="C9", padx=20, pady=20, command=myClick)
button29 = tk.Button(window, text="C10", padx=20, pady=20, command=myClick)

button30 = tk.Button(window, text="D1", padx=20, pady=20, command=myClick)
button31 = tk.Button(window, text="D2", padx=20, pady=20, command=myClick)
button32 = tk.Button(window, text="D3", padx=20, pady=20, command=myClick)
button33 = tk.Button(window, text="D4", padx=20, pady=20, command=myClick)
button34 = tk.Button(window, text="D5", padx=20, pady=20, command=myClick)
button35 = tk.Button(window, text="D6", padx=20, pady=20, command=myClick)
button36 = tk.Button(window, text="D7", padx=20, pady=20, command=myClick)
button37 = tk.Button(window, text="D8", padx=20, pady=20, command=myClick)
button38 = tk.Button(window, text="D9", padx=20, pady=20, command=myClick)
button39 = tk.Button(window, text="D10", padx=20, pady=20, command=myClick)

button40 = tk.Button(window, text="E1", padx=20, pady=20, command=myClick)
button41 = tk.Button(window, text="E2", padx=20, pady=20, command=myClick)
button42 = tk.Button(window, text="E3", padx=20, pady=20, command=myClick)
button43 = tk.Button(window, text="E4", padx=20, pady=20, command=myClick)
button44 = tk.Button(window, text="E5", padx=20, pady=20, command=myClick)
button45 = tk.Button(window, text="E6", padx=20, pady=20, command=myClick)
button46 = tk.Button(window, text="E7", padx=20, pady=20, command=myClick)
button47 = tk.Button(window, text="E8", padx=20, pady=20, command=myClick)
button48 = tk.Button(window, text="E9", padx=20, pady=20, command=myClick)
button49 = tk.Button(window, text="E10", padx=20, pady=20, command=myClick)

button50 = tk.Button(window, text="F1", padx=20, pady=20, command=myClick)
button51 = tk.Button(window, text="F2", padx=20, pady=20, command=myClick)
button52 = tk.Button(window, text="F3", padx=20, pady=20, command=myClick)
button53 = tk.Button(window, text="F4", padx=20, pady=20, command=myClick)
button54 = tk.Button(window, text="F5", padx=20, pady=20, command=myClick)
button55 = tk.Button(window, text="F6", padx=20, pady=20, command=myClick)
button56 = tk.Button(window, text="F7", padx=20, pady=20, command=myClick)
button57 = tk.Button(window, text="F8", padx=20, pady=20, command=myClick)
button58 = tk.Button(window, text="F9", padx=20, pady=20, command=myClick)
button59 = tk.Button(window, text="F10", padx=20, pady=20, command=myClick)

button60 = tk.Button(window, text="G1", padx=20, pady=20, command=myClick)
button61 = tk.Button(window, text="G2", padx=20, pady=20, command=myClick)
button62 = tk.Button(window, text="G3", padx=20, pady=20, command=myClick)
button63 = tk.Button(window, text="G4", padx=20, pady=20, command=myClick)
button64 = tk.Button(window, text="G5", padx=20, pady=20, command=myClick)
button65 = tk.Button(window, text="G6", padx=20, pady=20, command=myClick)
button66 = tk.Button(window, text="G7", padx=20, pady=20, command=myClick)
button67 = tk.Button(window, text="G8", padx=20, pady=20, command=myClick)
button68 = tk.Button(window, text="G9", padx=20, pady=20, command=myClick)
button69 = tk.Button(window, text="G10", padx=20, pady=20, command=myClick)

button70 = tk.Button(window, text="H1", padx=20, pady=20, command=myClick)
button71 = tk.Button(window, text="H2", padx=20, pady=20, command=myClick)
button72 = tk.Button(window, text="H3", padx=20, pady=20, command=myClick)
button73 = tk.Button(window, text="H4", padx=20, pady=20, command=myClick)
button74 = tk.Button(window, text="H5", padx=20, pady=20, command=myClick)
button75 = tk.Button(window, text="H6", padx=20, pady=20, command=myClick)
button76 = tk.Button(window, text="H7", padx=20, pady=20, command=myClick)
button77 = tk.Button(window, text="H8", padx=20, pady=20, command=myClick)
button78 = tk.Button(window, text="H9", padx=20, pady=20, command=myClick)
button79 = tk.Button(window, text="H10", padx=20, pady=20, command=myClick)

button80 = tk.Button(window, text="I1", padx=20, pady=20, command=myClick)
button81 = tk.Button(window, text="I2", padx=20, pady=20, command=myClick)
button82 = tk.Button(window, text="I3", padx=20, pady=20, command=myClick)
button83 = tk.Button(window, text="I4", padx=20, pady=20, command=myClick)
button84 = tk.Button(window, text="I5", padx=20, pady=20, command=myClick)
button85 = tk.Button(window, text="I6", padx=20, pady=20, command=myClick)
button86 = tk.Button(window, text="I7", padx=20, pady=20, command=myClick)
button87 = tk.Button(window, text="I8", padx=20, pady=20, command=myClick)
button88 = tk.Button(window, text="I9", padx=20, pady=20, command=myClick)
button89 = tk.Button(window, text="I10", padx=20, pady=20, command=myClick)

button90 = tk.Button(window, text="J1", padx=20, pady=20, command=myClick)
button91 = tk.Button(window, text="J2", padx=20, pady=20, command=myClick)
button92 = tk.Button(window, text="J3", padx=20, pady=20, command=myClick)
button93 = tk.Button(window, text="J4", padx=20, pady=20, command=myClick)
button94 = tk.Button(window, text="J5", padx=20, pady=20, command=myClick)
button95 = tk.Button(window, text="J6", padx=20, pady=20, command=myClick)
button96 = tk.Button(window, text="J7", padx=20, pady=20, command=myClick)
button97 = tk.Button(window, text="J8", padx=20, pady=20, command=myClick)
button98 = tk.Button(window, text="J9", padx=20, pady=20, command=myClick)
button99 = tk.Button(window, text="J10", padx=20, pady=20, command=myClick)

# Define Grid
window.columnconfigure(0, weight=1)
window.columnconfigure(1, weight=1)
window.columnconfigure(2, weight=1)
window.columnconfigure(3, weight=1)
window.columnconfigure(4, weight=1)
window.columnconfigure(5, weight=1)
window.columnconfigure(6, weight=1)
window.columnconfigure(7, weight=1)
window.columnconfigure(8, weight=1)
window.columnconfigure(9, weight=1)

window.rowconfigure(0, weight=1)
window.rowconfigure(1, weight=1)
window.rowconfigure(2, weight=1)
window.rowconfigure(3, weight=1)
window.rowconfigure(4, weight=1)
window.rowconfigure(5, weight=1)
window.rowconfigure(6, weight=1)
window.rowconfigure(7, weight=1)
window.rowconfigure(8, weight=1)
window.rowconfigure(9, weight=1)

# Place Widget
button00.grid(row=0, column=0)
button01.grid(row=0, column=1)
button02.grid(row=0, column=2)
button03.grid(row=0, column=3)
button04.grid(row=0, column=4)
button05.grid(row=0, column=5)
button06.grid(row=0, column=6)
button07.grid(row=0, column=7)
button08.grid(row=0, column=8)
button09.grid(row=0, column=9)

button10.grid(row=1, column=0)
button11.grid(row=1, column=1)
button12.grid(row=1, column=2)
button13.grid(row=1, column=3)
button14.grid(row=1, column=4)
button15.grid(row=1, column=5)
button16.grid(row=1, column=6)
button17.grid(row=1, column=7)
button18.grid(row=1, column=8)
button19.grid(row=1, column=9)

button20.grid(row=2, column=0)
button21.grid(row=2, column=1)
button22.grid(row=2, column=2)
button23.grid(row=2, column=3)
button24.grid(row=2, column=4)
button25.grid(row=2, column=5)
button26.grid(row=2, column=6)
button27.grid(row=2, column=7)
button28.grid(row=2, column=8)
button29.grid(row=2, column=9)

button30.grid(row=3, column=0)
button31.grid(row=3, column=1)
button32.grid(row=3, column=2)
button33.grid(row=3, column=3)
button34.grid(row=3, column=4)
button35.grid(row=3, column=5)
button36.grid(row=3, column=6)
button37.grid(row=3, column=7)
button38.grid(row=3, column=8)
button39.grid(row=3, column=9)

button40.grid(row=4, column=0)
button41.grid(row=4, column=1)
button42.grid(row=4, column=2)
button43.grid(row=4, column=3)
button44.grid(row=4, column=4)
button45.grid(row=4, column=5)
button46.grid(row=4, column=6)
button47.grid(row=4, column=7)
button48.grid(row=4, column=8)
button49.grid(row=4, column=9)

button50.grid(row=5, column=0)
button51.grid(row=5, column=1)
button52.grid(row=5, column=2)
button53.grid(row=5, column=3)
button54.grid(row=5, column=4)
button55.grid(row=5, column=5)
button56.grid(row=5, column=6)
button57.grid(row=5, column=7)
button58.grid(row=5, column=8)
button59.grid(row=5, column=9)

button60.grid(row=6, column=0)
button61.grid(row=6, column=1)
button62.grid(row=6, column=2)
button63.grid(row=6, column=3)
button64.grid(row=6, column=4)
button65.grid(row=6, column=5)
button66.grid(row=6, column=6)
button67.grid(row=6, column=7)
button68.grid(row=6, column=8)
button69.grid(row=6, column=9)

button70.grid(row=7, column=0)
button71.grid(row=7, column=1)
button72.grid(row=7, column=2)
button73.grid(row=7, column=3)
button74.grid(row=7, column=4)
button75.grid(row=7, column=5)
button76.grid(row=7, column=6)
button77.grid(row=7, column=7)
button78.grid(row=7, column=8)
button79.grid(row=7, column=9)

button80.grid(row=8, column=0)
button81.grid(row=8, column=1)
button82.grid(row=8, column=2)
button83.grid(row=8, column=3)
button84.grid(row=8, column=4)
button85.grid(row=8, column=5)
button86.grid(row=8, column=6)
button87.grid(row=8, column=7)
button88.grid(row=8, column=8)
button89.grid(row=8, column=9)

button90.grid(row=9, column=0)
button91.grid(row=9, column=1)
button92.grid(row=9, column=2)
button93.grid(row=9, column=3)
button94.grid(row=9, column=4)
button95.grid(row=9, column=5)
button96.grid(row=9, column=6)
button97.grid(row=9, column=7)
button98.grid(row=9, column=8)
button99.grid(row=9, column=9)

# Run
window.mainloop()